### ISSUE TITLE
boss，Is this not uploaded successfully? 

### ISSUE THREAD

**Issue by shumoLR** [Haoming02/comfyui-old-photo-restoration#5]
Is this not uploaded successfully? Now the github code base update failed, an error occurred, loading failed!
![image](https://github.com/user-attachments/assets/5d465dad-32d0-4da9-9cd4-59ef2efdd7c9)

After the update, the file was not found
![image](https://github.com/user-attachments/assets/0857a1a7-41cb-42a7-ac6e-162cda051796)
![image](https://github.com/user-attachments/assets/7ac2186a-e5e1-4866-97d0-216f42b40688)

**Comment by Haoming02** [comment]
Hmm, how did you install the Node?

**Comment by Haoming02** [comment]
I just tired installing the Node using the Manager, and it seemed to work correctly.

If you manually cloned the repo yourself, you need to also clone the submodule.

**Comment by shumoLR** [comment]
> Hmm, how did you install the Node?

Use the git clone method

**Comment by Haoming02** [comment]
> you also need to clone the submodule

`git submodule update --init --recursive`
